Bluez-DBus Utility Library: Characteristic Class Reference
Characteristic Class Reference abstract
Characteristic interface.
#include <characteristic.h>
Public Member Functions
virtual std::vector< u8 > ReadValue (std::map< std::string, sdbus::Variant > options={}) const =0
virtual void WriteValue (std::vector< u8 > value, std::map< std::string, sdbus::Variant > options={})=0
virtual void StartNotify ()
virtual void StopNotify ()
Characteristic (sdbus::IConnection &connection, std::string service_object_path, unsigned int index, std::string UUID, std::vector< std::string > flags={"read", "write"})
std::string getObjectPath () const
virtual ~Characteristic ()
Detailed Description
Characteristic interface.
Any characteristic must inherit from this, and it must provide a constructor with the signature:
MyCharacteristic::MyCharacteristic(sdbus::IConnection &connection, std::string service_object_path, unsigned int index, std::string UUID, std::vector<std::string> flags): Characteristic(connection,service_object_path,index,UUID,flags) { ... yourlogic ... }
Definition at line 35 of file characteristic.h.
Constructor & Destructor Documentation
Characteristic()
Characteristic::Characteristic (sdbus::IConnection & connection, std::string service_object_path, unsigned int index, std::string UUID, std::vector< std::string > flags = {"read", "write"})
Definition at line 24 of file characteristic.cpp.
~Characteristic()
virtual Characteristic::~Characteristic () inline virtual
Definition at line 64 of file characteristic.h.
Member Function Documentation
getObjectPath()
std::string Characteristic::getObjectPath () const
Definition at line 104 of file characteristic.cpp.
ReadValue()
virtual std::vector<u8> Characteristic::ReadValue (std::map< std::string, sdbus::Variant > options = {}) const pure virtual
@references:
gatt-api.txt -> GattCharacteristic1 <Confirm(), Flags>
Referenced by Characteristic().
StartNotify()
virtual void Characteristic::StartNotify () inline virtual
Definition at line 54 of file characteristic.h.
Referenced by Characteristic().
StopNotify()
virtual void Characteristic::StopNotify () inline virtual
Definition at line 55 of file characteristic.h.
Referenced by Characteristic().
WriteValue()
virtual void Characteristic::WriteValue (std::vector< u8 > value, std::map< std::string, sdbus::Variant > options = {}) pure virtual
Referenced by Characteristic().
The documentation for this class was generated from the following files:
ble/include/ble/characteristic.h
ble/src/characteristic.cpp